<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AssemblyName>Alexander.Gorbunov.Helium</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Alexander.Gorbunov.Helium</PackageId>
        <Title>Themed controls for .NET</Title>
        <Authors>Alexander Gorbunov</Authors>
        <RepositoryUrl>https://github.com/MrLinkDev/Helium</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
        <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="$(PackageLicenseFile)"/>
    </ItemGroup>

    <PropertyGroup>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <VersionPrefix>2.0.0</VersionPrefix>

        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>..\..\build\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>..\..\build\Release\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Page Update="Themes\Generic.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons\Paths\CloseIcon.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons\Paths\MaximizeIcon.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons\Paths\MinimizeIcon.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\HeBrushes.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\HeColors.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\HeDimensions.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\HeButton\Styles\Templates\HeButtonAttentionTemplate.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\HeButton\Styles\Templates\HeButtonNeutralTemplate.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\Icons\close_icon.png"/>
        <Resource Include="Resources\Icons\default_icon.png"/>
        <Resource Include="Resources\Icons\maximize_icon.png"/>
        <Resource Include="Resources\Icons\minimize_icon.png"/>
        <Resource Include="Resources\Icons\app_icon.png"/>
        <Resource Include="Resources\Icons\backspace_icon.png"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>
    <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
        <ItemGroup>
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths->WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))"/>
            <BuildOutputInPackage Include="$(NetCoreTargetingPackRoot)\Microsoft.NETCore.App.Host.$(NETCoreSdkRuntimeIdentifier)\$(BundledNETCoreAppPackageVersion)\runtimes\$(NETCoreSdkRuntimeIdentifier)\native\ijwhost.dll" Link="ijwhost.dll"/>
        </ItemGroup>
    </Target>

</Project>
