<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Page Update="Resources\Brushes.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
      <Page Update="Resources\Colors.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
      <Page Update="Resources\Dimensions.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>

</Project>
