<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>HeliumDemo</RootNamespace>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugType>none</DebugType>
      <OutputPath>..\Helium.Build\Release\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>x64</PlatformTarget>
      <OutputPath>..\Helium.Build\Debug\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Amethyst\Amethyst\Amethyst.vcxproj" />
      <ProjectReference Include="..\Helium\Helium.csproj" />
    </ItemGroup>

</Project>
