<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>HeliumDemo</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Helium.Button\Helium.Button.csproj" />
      <ProjectReference Include="..\Helium.CardView\Helium.CardView.csproj" />
      <ProjectReference Include="..\Helium.ImageButton\Helium.ImageButton.csproj" />
    </ItemGroup>

</Project>
