<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>12</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <AssemblyVersion>Ку</AssemblyVersion>
        <FileVersion>1.0.8.8</FileVersion>
        <AssemblyName>Alexander.Gorbunov.Helium</AssemblyName>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <PropertyGroup>
        <PackageId>Alexander.Gorbunov.Helium</PackageId>
        <Title>Themed controls for .NET</Title>
        <Authors>Alexander Gorbunov</Authors>
        <Version>1.0.8.8</Version>
        <RepositoryUrl>https://github.com/MrLinkDev/Helium</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
        <None Include="..\LICENSE.txt" Pack="true" PackagePath="$(PackageLicenseFile)"/>
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <PlatformTarget>x64</PlatformTarget>
        <OutputPath>..\Helium.Build\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <OutputPath>..\Helium.Build\Release\</OutputPath>
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <Page Update="Themes\Generic.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons\Paths\CloseIcon.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons\Paths\MaximizeIcon.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons\Paths\MinimizeIcon.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Brushes.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Colors.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Dimensions.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Resources\Icons.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Window\Styles\HeWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\CheckBox\Styles\HeCheckBox.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Button\Styles\HeButton.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Button\Styles\Templates\HeButtonBezelTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Button\Styles\Templates\HeButtonFlatTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\ImageButton\Styles\HeImageButton.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\ImageButton\Styles\Templates\HeImageButtonFlatTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\ImageButton\Styles\Templates\HeImageButtonBezelTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\ImageButton\Styles\Templates\HeImageButtonTransparentTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\XButton\Styles\HeXValueButton.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\XButton\Styles\Templates\HeXValueButtonFlatTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\XRadioButton\Styles\HeXRadioButton.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\XRadioButton\Styles\Templates\HeXRadioButtonFlatTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Window\Styles\HeDialogWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Indicator\Styles\Templates\HeConnectionIndicatorTemplates.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Indicator\Styles\HeIndicator.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Switch\Styles\HeSwitch.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Switch\Styles\HeSwitchToggle.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\XCheckValueButton\Styles\HeXCheckValueButton.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\TabControl\Styles\HeVTabLabel.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\Indicator\Styles\Templates\HeControllerIndicatorTemplates.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
        <Page Update="Controls\XPushButton\Styles\HeXPushButton.xaml">
          <Generator>MSBuild:Compile</Generator>
          <XamlRuntime>Wpf</XamlRuntime>
          <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\Icons\close_icon.png"/>
        <Resource Include="Resources\Icons\default_icon.png"/>
        <Resource Include="Resources\Icons\maximize_icon.png"/>
        <Resource Include="Resources\Icons\minimize_icon.png"/>
        <Resource Include="Resources\Icons\app_icon.png"/>
        <Resource Include="Resources\Icons\backspace_icon.png"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Amethyst\Amethyst\Amethyst.vcxproj"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>
    <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
        <ItemGroup>
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths->WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))"/>
            <BuildOutputInPackage Include="$(NetCoreTargetingPackRoot)\Microsoft.NETCore.App.Host.$(NETCoreSdkRuntimeIdentifier)\$(BundledNETCoreAppPackageVersion)\runtimes\$(NETCoreSdkRuntimeIdentifier)\native\ijwhost.dll" Link="ijwhost.dll"/>
        </ItemGroup>
    </Target>

</Project>
